pipeline{
  agent { label 'nodejs' }
  stages{
    stage ('checkout'){
      steps{
        checkout scm
      }
    }
    stage ('install modules'){
      steps{
        sh '''
          npm install --verbose -d 
          npm install --save classlist.js
        '''
      }
    }
    stage ('test'){
      steps{
        echo 'testing..'
        // sh '''
        //   $(npm bin)/ng test --single-run --browsers Chrome_no_sandbox
        // '''
      }
      post {
          always {
            // junit "test-results.xml"
            echo 'publishing'
          }
      }
    }
    stage ('code quality'){
      steps{
        // sh '$(npm bin)/ng lint'
        echo 'linting..'
      }
    }
    stage ('build') {
      steps{
        sh '$(npm bin)/ng build --prod --build-optimizer'
      }
    }
    stage ('build image') {
      steps{
        sh '''
          rm -rf node_modules
          oc start-build angular-5-example --from-dir=. --follow
        '''
      }
    }
  }
}
